name: Build and Release DXT

on:
  push:
    tags:
      - 'v*'  # Run on version tags (v1.0.0, v1.1.0, etc.)

jobs:
  build-dxt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dxt
      run: |
        python -m pip install --upgrade pip
        pip install dxt-tools
        
    - name: Build DXT package
      run: |
        dxt pack
        
    - name: Upload DXT artifact
      uses: actions/upload-artifact@v3
      with:
        name: dxt-package
        path: calibremcp.dxt
        
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        body: Automated DXT package release
        draft: false
        prerelease: false
        
    - name: Upload DXT package to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./calibremcp.dxt
        asset_name: calibremcp-${{ github.ref_name }}.dxt
        asset_content_type: application/octet-stream
